image: docker:19.03

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:19.03-dind

before_script:
    - docker info
    
build:
  stage: build
  script:
    - docker build -t kalka/steamcmd:latest .
    - docker run --rm kalka/steamcmd:latest +quit
    - docker tag kalka/steamcmd:latest 172.17.0.1/kalka/steamcmd:latest
    - docker push 172.17.0.1:5000/kalka/steamcmd