image: docker:19.03

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:19.03-dind

before_script:
    - docker info
    
build:
  stage: build
  script:
    - docker build -t kalka/steamcmd .
    - docker run --rm kalka/steamcmd +quit