# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  before_script:
    - docker info
  script:
    - docker build -t kalka/steamcmd .
  only:
    - master
    