image: docker

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:dind

before_script:
    - docker info
    
build:
  script:
    - docker build -t kalka/steamcmd .