image: docker:19.03

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:19.03-dind

before_script:
    - docker info
    
build:
  stage: build
  script:
    - docker build -t srcds/steamcmd:latest .
    - docker run --rm srcds/steamcmd:latest +quit
    - docker tag srcds/steamcmd:latest registry:5000/srcds/steamcmd
    - docker push registry:5000/srcds/steamcmd